#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  driveEncL,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveEncR,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  armBump,        sensorDigitalIn)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           A4,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           A1,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           Claw1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           R1,            tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight, encoderPort, dgtl3)
#pragma config(Motor,  port5,           L2YL3,         tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port6,           R2YR3,         tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight, encoderPort, dgtl3)
#pragma config(Motor,  port7,           L1,            tmotorVex393TurboSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port8,           A2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           A3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

/* DEFINE CONSTANTS */
int dumpHeight = 950; //Defines the height of the arm where the claw is opened.
int armLimit = 1300; //Defines the top of the arms range of motion.

/* GLOBAL INIT */
#define MAX_VOLTAGE 127 //Maximum voltage to be applied to a motor.
#define MIN_VOLTAGE (-127) //Minimum voltage to be applied to a motor.
#define CLAW_CLOSE_VAL 2300 //Defines the potentiometer value of where the claw is concidered "closed."
#define CLAW_OPEN_VAL 1920 //Defines the potentiometer value of where the claw is concidered "open."
#define inToMm 25.4 //Conversion factor for autonomous PID movement.

/*GLOBAL FUNCTIONS */

//Moves the arm at the given voltage.
void setArm(int voltage){
	motor(A1) = motor(A2) = motor(A3) = motor(A4) = voltage;
}

//Moves the claw at the given voltage.
void setClaw(int voltage){
	motor(Claw1) = motor(Claw2) = voltage;
}

//Drives the left drive at the given voltage.
void leftDrive(int voltage){
	motor(L1) = motor(L2YL3) = voltage;
}

//Drives the right drive at the given voltage.
void rightDrive(int voltage){
	motor(R1) = motor(R2YR3) = voltage;
}

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//INCLUDES
#include "Vex_Competition_Includes.c" //Main competition background code...do not modify!
#include "PID.h"
#include "Autonomous_Drive.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton(){
	//Set encoder values to 0
	SensorValue(driveEncL) = 0;
	SensorValue(driveEncR) = 0;
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  								          Claw PID Control Task                            */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

//These could be constants but leaving as variables allows them to be modified in the debugger "live"
float  claw_pid_Kp = 1.0;
float  claw_pid_Kd = 0.7;

//Define if PID is running. Set in other functions.
static bool clawPIDRunning = true;

//Define the value requested to PID move to.
float clawPIDRequestedValue;

task clawPIDController(){
	//Initialize variables.
	float  pidSensorCurrentValue;

	float  pidError;
	float  pidLastError;

	float  pidDerivative;
	float  pidDrive;

	//Set the first error to 0.
	pidLastError  = 0;

	while(true){
		//Read the sensor value and scale.
		pidSensorCurrentValue = SensorValue[clawPot];

		//Calculate error.
		pidError = (pidSensorCurrentValue - clawPIDRequestedValue);

		//Calculate the derivative.
		pidDerivative = pidError - pidLastError;
		pidLastError  = pidError;

		//If PID is running calculate the drive and set the motor.
		if(clawPIDRunning){
			// calculate drive
			pidDrive = (claw_pid_Kp * pidError) + (claw_pid_Kd * pidDerivative);

			// limit drive
			if(pidDrive > MAX_VOLTAGE)
				pidDrive = MAX_VOLTAGE;
			if(pidDrive < MIN_VOLTAGE)
				pidDrive = MIN_VOLTAGE;

			// send to motor
			setClaw(pidDrive);
		}

		// Run task at 50Hz
		wait1Msec(25);
	}
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  								          Arm PID Control Task                             */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

//These could be constants but leaving as variables allows them to be modified in the debugger "live"
float  arm_pid_Kp = 2.0;
float  arm_pid_Kd = 1.4;

//Define if PID is running. Set in other functions.
static bool armPIDRunning = true;

//Define the value requested to PID move to.
float armPIDRequestedValue;

task armPIDController(){
	//Initialize variables.
	float  pidSensorCurrentValue;

	float  pidError;
	float  pidLastError;

	float  pidDerivative;
	float  pidDrive;

	//Set the first error to 0.
	pidLastError  = 0;

	while(true){
		//Read the sensor value and scale.
		pidSensorCurrentValue = SensorValue[I2C_1];

		//Calculate error.
		pidError = (armPIDRequestedValue - pidSensorCurrentValue);

		//Calculate the derivative.
		pidDerivative = pidError - pidLastError;
		pidLastError  = pidError;

		//If PID is running calculate the drive and set the motor.
		if(armPIDRunning){
			// calculate drive
			pidDrive = (arm_pid_Kp * pidError) + (arm_pid_Kd * pidDerivative);

			// limit drive
			if(pidDrive > MAX_VOLTAGE)
				pidDrive = MAX_VOLTAGE;
			if(pidDrive < MIN_VOLTAGE)
				pidDrive = MIN_VOLTAGE;

			// send to motor
			setArm(pidDrive);
		}

		// Run task at 50Hz
		wait1Msec(25);
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous(){
	drivePID(72 * inToMm);
	turnPID(90);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//ARCADE DRIVE SYSTEM
void arcadeDrive(){
	leftDrive(vexRT(Ch3) + vexRT(Ch1));
	rightDrive(vexRT(Ch3) - vexRT(Ch1));
}

//Returns the true speed of the robot based on imput.
char trueSpeed(int power) {
	char tsArray[128] =
	{
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 21, 21, 22, 22, 22, 23, 24, 24,
		25, 25, 25, 25, 26, 27, 27, 28, 28, 28,
		28, 29, 30, 30, 30, 31, 31, 32, 32, 32,
		33, 33, 34, 34, 35, 35, 35, 36, 36, 37,
		37, 37, 37, 38, 38, 39, 39, 39, 40, 40,
		41, 41, 42, 42, 43, 44, 44, 45, 45, 46,
		46, 47, 47, 48, 48, 49, 50, 50, 51, 52,
		52, 53, 54, 55, 56, 57, 57, 58, 59, 60,
		61, 62, 63, 64, 65, 66, 67, 67, 68, 70,
		71, 72, 72, 73, 74, 76, 77, 78, 79, 79,
		80, 81, 83, 84, 84, 86, 86, 87, 87, 88,
		88, 89, 89, 90, 90,127,127,127
	};
	return ((power>0)?1:-1)*tsArray[power*((power>0)?1:-1)];
}

//Tank Control Based on Real Imput
void tankDrive(){
	rightDrive(trueSpeed(vexRT[Ch3]));
	leftDrive(trueSpeed(vexRT[Ch2]));
}

//CLAW CONTROL
void userClaw(){
	if(vexRT(Btn5U)){ //If arm close button is pushed close the arm at full voltage.
		setClaw(MIN_VOLTAGE);
		clawPIDRunning = false;
	}
	else if(vexRT(Btn6U)){ //If arm open button is pushed open the arm at full voltage.
		setClaw(MAX_VOLTAGE);
		clawPIDRunning = false;
	}
	else if(SensorValue(clawPot) >= CLAW_CLOSE_VAL && !clawPIDRunning){ //If arm is not controlled, but closed past close point give a gipping voltage.
		setClaw(-20);
	}
	else if(!clawPIDRunning){ //Else, claw will not power.
		setClaw(0);
	}
}

//ARM CONTROL SYSTEM
void userArm(){
	if (vexRT(Btn6D)){ //If arm button is pushed set the PID requested value to dump and to close the claw.
		armPIDRunning = true;
		armPIDRequestedValue = armLimit;
		clawPIDRunning = true;
		clawPIDRequestedValue = CLAW_CLOSE_VAL+250;
	}
	if(!armPIDRunning && SensorValue(armBump) == 0){ //If the arm is at the bottom hold it down and zero the encoder.
		setArm(-10); //Hold voltage applied when claw is at the base.
		SensorValue(I2C_1) = 0; //Sets the encoder on the arm to 0.
	}
	else if(!armPIDRunning){ //If the arm is moving down give it the minimum voltage.
		setArm(MIN_VOLTAGE); //Downward voltage.
	}
	else if(SensorValue(I2C_1)+10 >= armLimit){ //If the arm has reached its target disable PID.
		armPIDRunning = false;
	}
	else if(SensorValue(I2C_1) > dumpHeight){ //If the arm is running, above the dumping value open the claw.
		clawPIDRunning = true;
		clawPIDRequestedValue = CLAW_OPEN_VAL; //Open claw
	}
}

float testLeft;
float testRight;

/* USER CONTROL CODE */
task usercontrol(){
	//Init claw PID task:
	startTask(clawPIDController);
	clawPIDRunning = false;
	clawPIDRequestedValue = CLAW_OPEN_VAL;

	//Init arm PID task:
	startTask(armPIDController);
	armPIDRunning = false;

	//Loop through control systems.
	while (true)
	{
		testLeft = SensorValue(driveEncL);
		testRight = SensorValue(driveEncR);

		//User control drive program:
		tankDrive();
		//arcadeDrive();

		//User control claw program:
		userClaw();

		//User control arm program:
		userArm();
	}
}
