#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  driveEncL,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveEncR,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  armBump,        sensorDigitalIn)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           R4,            tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           A1,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           Claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           R1,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           L2YL3,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           R2YR3,         tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           L1,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           A2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           A3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          L4,            tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

/* DEFINE CONSTANTS */
int dumpHeight = 1000;
int armLimit = 1300;


// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  pid control task                                                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
#define PID_DRIVE_MAX       127
#define PID_DRIVE_MIN     (-127)

// These could be constants but leaving
// as variables allows them to be modified in the debugger "live"
float  pid_Kp = 1.0;
float  pid_Kd = 0.5;
float  deltaD = 20;

static bool pidRunning = true;
float pidRequestedValue;
float clawPIDOutput;

task pidController()
{
	float  pidSensorCurrentValue;

	float  pidError;
	float  pidLastError;
	float  pidIntegral;
	float  pidDerivative;
	float  pidDrive;

	// Init the variables - thanks Glenn :)
	pidLastError  = 0;

	while( true )
	{

		// Read the sensor value and scale
		pidSensorCurrentValue = SensorValue[ clawPot ];

		// calculate error
		pidError = (pidSensorCurrentValue - pidRequestedValue)/10;

		// calculate the derivative
		pidDerivative = pidError - pidLastError;
		pidLastError  = pidError;

		// Is PID control active ?
		if( pidRunning )
		{

			// calculate drive
			pidDrive = (pid_Kp * pidError) + (pid_Kd * pidDerivative);

			// limit drive
			if( pidDrive > PID_DRIVE_MAX )
				pidDrive = PID_DRIVE_MAX;
			if( pidDrive < PID_DRIVE_MIN )
				pidDrive = PID_DRIVE_MIN;

			// send to motor
			motor(Claw) = pidDrive ;
		}
		else
		{
		}

		// Run at 50Hz
		wait1Msec( 25 );
	}
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//Moves the arm at the given voltage.
void setArm(int voltage){
	motor(A1) = motor(A2) = motor(A3) = voltage;
}

//Drives the left drive at the given voltage.
void leftDrive(int voltage){
	motor(L1) = motor(L2YL3) = motor(L4) = voltage;
}

//Drives the right drive at the given voltage.
void rightDrive(int voltage){
	motor(R1) = motor(R2YR3) = motor(R4) = voltage;
}

//ARCADE DRIVE SYSTEM
void arcadeDrive(){
	leftDrive(vexRT(Ch3) + vexRT(Ch1));
	rightDrive(vexRT(Ch3) - vexRT(Ch1));
}

//TANK DRIVE SYSTEM
void tankDrive(){
	leftDrive(vexRT(Ch3));
	rightDrive(vexRT(Ch2));
}

//CLAW CONTROL SYSTEM
void userClaw(){
	if(vexRT(Btn5U)){
		//pidRequestedValue = 1350;
		pidRunning = false;
		motor(Claw) = 127;
	}
	else if(vexRT(Btn6U)){
		pidRunning = true;
		pidRequestedValue = 2900;
	}
	else if(!pidRunning){
		motor(Claw) = 10;
	}


	//motor(Claw) = -127*vexRT(Btn5U) + 127*vexRT(Btn6U);
}

//ARM CONTROL SYSTEM
void userArm(){
	if (vexRT(Btn6D) && SensorValue(I2C_1) < dumpHeight){ //Arm moving up
		setArm(127); //Full upward voltage.
	}
	else if(vexRT(Btn6D) && SensorValue(I2C_1) < armLimit){ //Arm moving up
		setArm(90); //Full upward voltage.
		pidRunning = true;
		pidRequestedValue = 2900; //Open claw
	}
	else if(SensorValue(armBump) == 0){ //Arm at bottom
		setArm(-10); //Hold voltage applied when claw is at the base.
		SensorValue(I2C_1) = 0; //TODO: read from I2C the integrated encoder data and write functions to manipulate.
	}
	else{ //Arm moving down
		setArm(-50); //Full downward voltage.
	}
}
bool armBumpVal;

task usercontrol()
{
	startTask( pidController );
	pidRunning = true;

	// User control code here, inside the loop
	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		armBumpVal = SensorValue(armBump) == 0;

		//User control drive program:
		//tankDrive();
		arcadeDrive();

		//User control claw program:
		userClaw();

		//User control arm program:
		userArm();
	}
}
